version: "3"
services:
  apache:
    build:
      context: ./apache
    volumes:
      - "../:/var/www/htdocs"
      - "./apache/confs:/usr/local/apache2/conf/custom.conf.d"
    ports:
      - "80:80"
    depends_on:
      - php
#    networks:
#      default:
#        ipv4_address: 10.5.0.5

  php:
    build:
      context: ./php
    tty: true
    volumes:
      - "../:/var/www/htdocs"
    ports:
      - "9000:9000"
    depends_on:
      - db
    environment:
      - MYSQL_USER
      - MYSQL_PASS
      - MYSQL_DATABASE
      - WPMARTINI_DBNAME
      - WPMARTINI_DBUSER
      - WPMARTINI_DBPASS
      - WPMARTINI_DBHOST
#    networks:
#      default:
#        ipv4_address: 10.5.0.7

  db:
    image: mariadb
    tty: true
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD
      - MYSQL_USER
      - MYSQL_PASSWORD
      - MYSQL_DATABASE
    volumes:
      - ./storage/mysql:/var/lib/mysql
    ports:
      - 3306:3306
#    networks:
#      default:
#        ipv4_address: 10.5.0.10
  adminer:
    image: adminer
    restart: always
    depends_on:
      - db
    ports:
      - 9001:8080
#    networks:
#      default:
#        ipv4_address: 10.5.0.11

networks:
  default:
#      external: true
      driver: bridge
#    ipam:
#      config:
#        - subnet: 10.5.0.0/16

